version: '3.4'

services:
  timebattleapi:
    image: timebattleapi
    build:
      context: .
      dockerfile: TimebattleApi/Dockerfile
    depends_on:
      - mongomain
      - grainssilo
      - kafka
    environment:
      - CLUSTER_CONNECTION_STRING=mongodb://mongomain:27017
      - KAFKA=kafka:9092

  managementapi:
    image: managementapi
    build:
      context: .
      dockerfile: ManagementApi/Dockerfile
    depends_on:
      - mongomain
      - grainssilo
    environment:
      - CLUSTER_CONNECTION_STRING=mongodb://mongomain:27017


  grainssilo:
    image: grainssilo
    build:
      context: .
      dockerfile: GrainsSilo/Dockerfile
    ports:
      - 11111:11111
      - 30000:30000
    links:
      - mongomain
      - mongoplayers
      - mongoworld
    depends_on:
      - mongomain
      - mongoplayers
      - mongoworld
      - kafka
    environment:
      - CLUSTER_CONNECTION_STRING=mongodb://mongomain:27017
      - PLAYER_CONNECTION_STRING=mongodb://mongoplayers:27017
      - WORLD_CONNECTION_STRING=mongodb://mongoworld:27017
      - SELF=grainssilo
      - KAFKA=kafka:9092

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.64
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_CREATE_TOPICS: "Sector:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  mongomain:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/log
#    volumes:
#      - d:/timebattle/main/db:/data/db
#      - d:/timebattle/main/log:/data/log
    ports:
      - 27018:27017
    command: mongod --smallfiles

  mongoplayers:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/log
#    volumes:
#      - d:/timebattle/players/db:/data/db
#      - d:/timebattle/players/log:/data/log
    ports:
      - 27019:27017
    command: mongod --smallfiles 

  mongoworld:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/log
#    volumes:
#      - d:/timebattle/world/db:/data/db
#      - d:/timebattle/world/log:/data/log
    ports:
      - 27020:27017
    command: mongod --smallfiles