version: '3.4'

services:
  timebattleapi:
    image: timebattleapi
    build:
      context: .
      dockerfile: TimebattleApi/Dockerfile
    depends_on:
      - mongomain
      - grainssilo
      - redis
    environment:
      - CLUSTER_CONNECTION_STRING=mongodb://mongomain:27017
      - REDIS=redis:6379

  managementapi:
    image: managementapi
    build:
      context: .
      dockerfile: ManagementApi/Dockerfile
    depends_on:
      - mongomain
      - grainssilo
    environment:
      - CLUSTER_CONNECTION_STRING=mongodb://mongomain:27017


  grainssilo:
    image: grainssilo
    build:
      context: .
      dockerfile: GrainsSilo/Dockerfile
    ports:
      - 11111:11111
      - 30000:30000
    links:
      - mongomain
      - mongoplayers
      - mongoworld
    depends_on:
      - mongomain
      - mongoplayers
      - mongoworld
      - redis
    environment:
      - CLUSTER_CONNECTION_STRING=mongodb://mongomain:27017
      - PLAYER_CONNECTION_STRING=mongodb://mongoplayers:27017
      - WORLD_CONNECTION_STRING=mongodb://mongoworld:27017
      - SELF=grainssilo
      - REDIS=redis:6379

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 16379:6379

  mongomain:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/log
#    volumes:
#      - d:/timebattle/main/db:/data/db
#      - d:/timebattle/main/log:/data/log
    ports:
      - 27018:27017
    command: mongod --smallfiles

  mongoplayers:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/log
#    volumes:
#      - d:/timebattle/players/db:/data/db
#      - d:/timebattle/players/log:/data/log
    ports:
      - 27019:27017
    command: mongod --smallfiles 

  mongoworld:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/log
#    volumes:
#      - d:/timebattle/world/db:/data/db
#      - d:/timebattle/world/log:/data/log
    ports:
      - 27020:27017
    command: mongod --smallfiles